// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgHvrFLRxLKMa73qO_eb1j8NrFLoEIHDY',
    appId: '1:978431054644:web:e0ae7a5c998d8960cf4b61',
    messagingSenderId: '978431054644',
    projectId: 'spoonshare-meal',
    authDomain: 'spoonshare-meal.firebaseapp.com',
    databaseURL: 'https://spoonshare-meal-default-rtdb.firebaseio.com',
    storageBucket: 'spoonshare-meal.appspot.com',
    measurementId: 'G-DTHELS4X4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAyb_1VNm4DmMpVHe2F2F2It1tdQbo3Tw',
    appId: '1:978431054644:android:3f09951bf5d4a82fcf4b61',
    messagingSenderId: '978431054644',
    projectId: 'spoonshare-meal',
    databaseURL: 'https://spoonshare-meal-default-rtdb.firebaseio.com',
    storageBucket: 'spoonshare-meal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY_fDAkghN8c_w21Zlsclm0guWpAS7PqU',
    appId: '1:978431054644:ios:5c876cd9a863638ccf4b61',
    messagingSenderId: '978431054644',
    projectId: 'spoonshare-meal',
    databaseURL: 'https://spoonshare-meal-default-rtdb.firebaseio.com',
    storageBucket: 'spoonshare-meal.appspot.com',
    androidClientId: '978431054644-3th7br9m1ebdgl57smeibv8431sk80c2.apps.googleusercontent.com',
    iosClientId: '978431054644-1bu54f0paqb8rvdapmtie0k5rkdm96hh.apps.googleusercontent.com',
    iosBundleId: 'com.spoonshare',
  );
}
